### ISSUE TITLE
Exception in Tkinter callback

### ISSUE THREAD

**Issue by davidosomething** [timeyyy/pytknvim#10]
did a pip upgrade to the latest version, same setup as previous tickets

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/david/.local/pyenv/versions/3.5.1/lib/python3.5/tkinter/__init__.py", line 1549, in __call__
    return self.func(*args)
  File "/Users/david/.local/pyenv/versions/3.5.1/lib/python3.5/tkinter/__init__.py", line 596, in callit
    func(*args)
  File "/Users/david/.local/pyenv/versions/3.5.1/lib/python3.5/site-packages/pytknvim/tk_ui.py", line 250, in resize
    self.unbind_resize()
  File "/Users/david/.local/pyenv/versions/3.5.1/lib/python3.5/site-packages/pytknvim/tk_ui.py", line 144, in unbind_resize
    self.text.unbind('<Configure>', self._configure_id)
  File "/Users/david/.local/pyenv/versions/3.5.1/lib/python3.5/tkinter/__init__.py", line 1105, in unbind
    self.deletecommand(funcid)
  File "/Users/david/.local/pyenv/versions/3.5.1/lib/python3.5/tkinter/__init__.py", line 441, in deletecommand
    self.tk.deletecommand(name)
_tkinter.TclError: can't delete Tcl command
```

video http://screencast.com/t/n0EGFgwEUQY

**Comment by timeyyy** [comment]
unreproducible on ubuntu 12.04, py3.4. Thanks for reporting the issue.
